# Generated by Django 6.0.6 on 2026-06-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areaofintrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areaofintrest.district')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_carbon_stock', models.FloatField(help_text='tonnes C')),
                ('estimated_change', models.FloatField(help_text='tonnes C change since last analysis')),
                ('ai_summary', models.TextField(blank=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisrun')),
            ],
        ),
    ]
