# Generated by Django 6.0.6 on 2026-07-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('areaofintrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonestimate',
            name='built_up_area_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carbonestimate',
            name='cropland_area_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carbonestimate',
            name='forest_area_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carbonestimate',
            name='other_area_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='areaofintrest.district'),
        ),
        migrations.AlterField(
            model_name='carbonestimate',
            name='analysis_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_estimate', to='analysis.analysisrun'),
        ),
        migrations.AlterField(
            model_name='carbonestimate',
            name='estimated_carbon_stock',
            field=models.FloatField(default=0, help_text='tonnes C'),
        ),
        migrations.AlterField(
            model_name='carbonestimate',
            name='estimated_change',
            field=models.FloatField(default=0, help_text='tonnes C change from 2020 to 2021'),
        ),
    ]
